module.exports = {
    "ceres": [
        "jupiter junction",
        "to jupiter",
        "to mars",
        "seimeni",
        "gabii",
        "gate crash",
        "pallas",
        "bode",
        "vedic",
        "varro",
        "thon",
        "olla",
        "nuovo",
        "ludi",
        "lex",
        "kiste",
        "ker",
        "hapke",
        "gefion",
        "exta",
        "egeria",
        "draco",
        "cinxia",
        "cerium",
        "casta",
        "albedo"
    ],
    "venus": [
        "romula",
        "malva",
        "tethra",
        "conclave",
        "kiliken",
        "fossa",
        "venera",
        "linea",
        "v prime",
        "e gate",
        "aphrodite",
        "tessera",
        "cytherean",
        "ishtar",
        "unda",
        "vesper",
        "montes",
        "vesper relay",
        "to earth",
        "mercury junction",
        "to mercury"
    ],
    "phobos": [
        "memphis",
        "zeugma",
        "shifting sands",
        "gate crash",
        "to mars",
        "to void",
        "conclave",
        "roche",
        "kepler",
        "gulliver",
        "monolith",
        "d'arrest",
        "shklovsky",
        "sharpless",
        "wendell",
        "opik",
        "todd",
        "skyresh",
        "iliad",
        "stickney",
        "drunlo",
        "grildrig",
        "limtoc",
        "hall",
        "reldresal",
        "clustril"
    ],
    "saturn": [
        "caracol",
        "piscinas",
        "birog",
        "cephalon capture",
        "annihilation",
        "lunaro arena",
        "(variant) cephalon capture",
        "(variant) team annihilation",
        "(variant) annihilation",
        "team annihilation",
        "kronia relay",
        "to jupiter",
        "uranus junction",
        "to uranus",
        "hyperion",
        "rhea",
        "enceladus",
        "telesto",
        "anthe",
        "tethys",
        "pallene",
        "helene",
        "mimas",
        "janus",
        "numa",
        "methone",
        "dione",
        "epimetheus",
        "cassini",
        "phoebe",
        "calypso",
        "aegaeon",
        "pandora",
        "iapetus",
        "keeler",
        "titan"
    ],
    "sedna": [
        "amarna",
        "sangeru",
        "nemed",
        "conclave",
        "to pluto",
        "to void",
        "kappa",
        "hyosube",
        "jengu",
        "undine",
        "adaro",
        "camenae",
        "vodyanoi",
        "rusalka",
        "berehynia",
        "phithale",
        "selkie",
        "kelpie",
        "naga",
        "nakki",
        "marid",
        "tikoloshe",
        "merrow",
        "ponaturi",
        "hydron",
        "charybdis",
        "graeae",
        "scylla",
        "yam",
        "veles",
        "tiamat",
        "yemaja"
    ],
    "uranus": [
        "ur",
        "assur",
        "sealab",
        "sealab",
        "sealab",
        "sealab",
        "sealab",
        "titania",
        "juliet",
        "setebos",
        "puck",
        "mab",
        "stephano",
        "trinculo",
        "bianca",
        "oberon",
        "cordelia",
        "ariel",
        "sycorax",
        "prospero",
        "perdita",
        "portia",
        "caliban",
        "umbriel",
        "ophelia",
        "cupid",
        "cressida",
        "rosalind",
        "miranda",
        "caelus",
        "desdemona",
        "neptune junction",
        "to neptune",
        "to saturn"
    ],
    "eris": [
        "akkad",
        "zabala",
        "kuiper relay",
        "to pluto",
        "lugh",
        "conclave",
        "acanth",
        "ascar",
        "brugia",
        "candiru",
        "cosis",
        "cyath",
        "giardia",
        "gnathos",
        "lepis",
        "histo",
        "hymeno",
        "isos",
        "ixodes",
        "kala-azar",
        "nimus",
        "oestrus",
        "psoro",
        "ranova",
        "saxis",
        "xini",
        "solium",
        "sparga",
        "naeglar",
        "viver",
        "jordas golem assassinate",
        "<raid> the jordas verdict",
        "mutalist alad v assassinate"
    ],
    "earth": [
        "coba",
        "tikal",
        "strata relay",
        "mars junction",
        "to mars",
        "to lua",
        "venus junction",
        "to venus",
        "gate crash",
        "gate crash",
        "gate crash",
        "pacific",
        "oro",
        "lith",
        "e prime",
        "everest",
        "eurasia",
        "mantle",
        "<raid> the law of retribution",
        "<nightmare_raid> the law of retribution (nightmare)",
        "cervantes",
        "cambria",
        "gaia",
        "mariana",
        "erpo",
        "maroo's bazaar"
    ],
    "neptune": [
        "yursa",
        "kelashin",
        "buarainech",
        "pluto junction",
        "to pluto",
        "to uranus",
        "to void",
        "cephalon capture",
        "galatea",
        "naiad",
        "laomedeia",
        "halimede",
        "psamathe",
        "proteus",
        "larissa",
        "sao",
        "despina",
        "neso",
        "the index",
        "the index",
        "the index",
        "the index",
        "triton",
        "nereid",
        "salacia",
        "thalassa"
    ],
    "pluto": [
        "sechura",
        "hieracon",
        "corb",
        "orcus relay",
        "to derelict",
        "eris junction",
        "to eris",
        "to neptune",
        "sedna junction",
        "to sedna",
        "conclave",
        "oceanum",
        "narcissus",
        "minthe",
        "acheron",
        "cerberus",
        "regna",
        "hades",
        "cypress",
        "outer terminus",
        "hydra",
        "nix",
        "palus",
        "charon"
    ],
    "jupiter": [
        "sinai",
        "cameria",
        "bres",
        "to ceres",
        "europa junction",
        "to europa",
        "saturn junction",
        "to saturn",
        "conclave",
        "thebe",
        "elara",
        "carpo",
        "io",
        "metis",
        "callisto",
        "themisto",
        "ananke",
        "carme",
        "ganymede",
        "adrastea",
        "galilea",
        "amalthea"
    ],
    "europa": [
        "larzac",
        "cholistan",
        "leonov relay",
        "to jupiter",
        "to void",
        "cryotic front",
        "cryotic front",
        "cryotic front",
        "cryotic front",
        "conclave",
        "abaddon",
        "armaros",
        "baal",
        "eligor",
        "gamygyn",
        "lillith",
        "morax",
        "naamah",
        "ose",
        "paimon",
        "shax",
        "sorath",
        "valac",
        "valefor",
        "orias",
        "zagan",
        "beleth",
        "kokabiel"
    ],
    "mars": [
        "kadesh",
        "wahiba",
        "elatha",
        "ceres junction",
        "to ceres",
        "to earth",
        "phobos junction",
        "to phobos",
        "alator",
        "tharsis",
        "ares",
        "quirinus",
        "ultor",
        "augustus",
        "olympus",
        "arcadia",
        "martialis",
        "arval",
        "ara",
        "spear",
        "silvanus",
        "hellas",
        "gradivus",
        "vallis",
        "syrtis",
        "war"
    ],
    "derelict": [
        "to pluto",
        "orokin derelict capture",
        "orokin derelict defense",
        "orokin derelict exterminate",
        "orokin derelict mobile defense",
        "orokin derelict sabotage",
        "orokin derelict survival",
        "orokin derelict assassinate"
    ],
    "mercury": [
        "balor",
        "larunda relay",
        "to venus",
        "m prime",
        "tolstoj",
        "caloris",
        "elion",
        "lares",
        "neruda",
        "eminescu",
        "boethius",
        "odin",
        "suisei",
        "pantheon",
        "verdi",
        "terminus",
        "caduceus",
        "apollodorus"
    ],
    "lua": [
        "to earth",
        "plato",
        "grimaldi",
        "tycho",
        "copernicus",
        "st\u00f6fler",
        "pavlov",
        "zeipel"
    ],
    "void": [
        "teshub",
        "hepit",
        "taranis",
        "tiwaz",
        "stribog",
        "ani",
        "ukko",
        "oxomoco",
        "belenus",
        "mot",
        "aten",
        "marduk",
        "mithra",
        "to europa",
        "to neptune",
        "to phobos",
        "to sedna"
    ],
    "kuva fortress": [
        "koro",
        "nabuk",
        "rotuma",
        "taveuni",
        "tamu",
        "dakata",
        "pago",
        "garus"
    ]
}